### ISSUE TITLE
[Community] Prepare for the new version

### ISSUE THREAD

**Issue by Starnop** [dragonflyoss/Dragonfly#1038]
Now we are ready to publish a new version that is planned to be the GA version for Dragonfly. And the scheduled release time is 2019.11.15 Beijing time. In order to accomplish this goal, we still need to do something.

Issues:
- [x] More stability testing (@Starnop 11.14.2019) 
- [ ] Support hot reload for config files #959 (@lowzj @SataQiu 11.10.2019) 
- [x] Dfdaemon calls dfget and zombie mileage occurs #997 (@zhouhaibing089   11.03.2019) 
- [x] fix valid ip not support ipv6 #1034 #334 (@fengzixu 11.10.2019)  
- [x] add helm chart for Dragonfly （ @Starnop 11.10.2019）

PRs:
- [x] feature:registry mirror support direct param. #942 (@inoc603 @Starnop  11.06.2019)
- [x] feature: support multi https backend #757 (@inoc603 @lowzj 11.08.2019) 

@dragonflyoss/dragonfly-maintainers 
If you find anything else that needs to be done in the GA version, please add it directly to the issue.

@ All contributors 
If you find anything else that needs to be done in the GA version, please don't hesitate to commit to this issue.

Let's deliver a perfect GA version for the community. 😄

**Comment by allencloud** [comment]
Could we nail down specific time for the detailed work? @Starnop Otherwise, maybe little productivity could be guaranteed.

**Comment by zhouhaibing089** [comment]
IPv6 support needs more work, I guess. In my opinion, the GA version probably should just be fixing usability issues instead of making it working with IPv6. Probably we can clearly say that we only support IPv4, and get rid of irrelevant errors to reduce frictions.

**Comment by zhouhaibing089** [comment]
I think we also need to specifically clarify which kind of configuration can be reloaded automatically. Not all of them can be obviously, for example, the port can't be changed unless give it a restart. I've seen projects(prow for example) which simply updates configuration every minute.

**Comment by zhouhaibing089** [comment]
I hope https://github.com/dragonflyoss/Dragonfly/pull/1041 will fix #997.

**Comment by Starnop** [comment]
> I think we also need to specifically clarify which kind of configuration can be reloaded automatically. Not all of them can be obviously, for example, the port can't be changed unless we give it a restart. I've seen projects(prow for example) which simply updates configuration every minute.

I agree with you. And I think we can make more discussion in the issue #959. 

And in fact, viper also supports the ability to have your application live read a config file while running.

**Comment by Starnop** [comment]
> IPv6 support needs more work, I guess. In my opinion, the GA version probably should just be fixing usability issues instead of making it working with IPv6. Probably we can clearly say that we only support IPv4, and get rid of irrelevant errors to reduce frictions.

If that, we should make dfget should not obtain the IPv6 address firstly. also cc/ @fengzixu

**Comment by fengzixu** [comment]
> > IPv6 support needs more work, I guess. In my opinion, the GA version probably should just be fixing usability issues instead of making it working with IPv6. Probably we can clearly say that we only support IPv4, and get rid of irrelevant errors to reduce frictions.
> 
> If that, we should make dfget should not obtain the IPv6 address firstly. also cc/ @fengzixu

emmm, it depends on our requirement of a new version. If we just don't want to release this function now, I will modify the dfget's logic to ban the IPv6 address firstly.

**Comment by Starnop** [comment]
> > > IPv6 support needs more work, I guess. In my opinion, the GA version probably should just be fixing usability issues instead of making it working with IPv6. Probably we can clearly say that we only support IPv4, and get rid of irrelevant errors to reduce frictions.
> > 
> > 
> > If that, we should make dfget should not obtain the IPv6 address firstly. also cc/ @fengzixu
> 
> emmm, it depends on our requirement of a new version. If we just don't want to release this function now, I will modify the dfget's logic to ban the IPv6 address firstly.

Could you please make an assessment of the workload firstly? If it needs a lot of work, I  think it's OK to ban the IPv6 address firstly. THX.

**Comment by xq2248** [comment]
File preheating feature has not been migrated yet.

POST ​/preheats Create a Preheat Task
GET ​/preheats List Preheat Tasks
GET ​/preheats​/{id} Get a preheat task

**Comment by Starnop** [comment]
> File preheating feature has not been migrated yet.
> 
> POST ​/preheats Create a Preheat Task
> GET ​/preheats List Preheat Tasks
> GET ​/preheats​/{id} Get a preheat task

Thanks for pointing this out. And what do you think of we planned for it in the version immediately after GA? And for the GA version, we try to ensure the stability of the system as much as possible. WDYT? 😄

**Comment by xq2248** [comment]
Pretty good.

**Comment by Starnop** [comment]
We have published the 1.0.0 version without feature [hot reload for config files]. And we should finish it later.
